### ISSUE TITLE
Can you explain please.

### ISSUE THREAD

**Issue by Danila24ru** [KillaMaaki/ReliableNetcode.NET#2]
How I can use it in Netcode.io? Where (in what class) I should define ``` var relieableEndpoint = ReliableEndpoint();``` and use it ?
Here https://github.com/KillaMaaki/Unity-Netcode.IO/blob/master/Assets/UnityNetcodeIO/Test/Scripts/TestNetcodeIOServer.cs   or?
Sorry for noob question but I really need reliable channel for game)

**Comment by GlaireDaggers** [comment]
OK, so first let's just consider this from the point of view of the client, since that's a simpler case. The "Client" class is the sole point of communication with the server. Think of it like your socket.
ReliableEndpoint is intended to be itself another abstraction on top of a socket. The idea is that you provide the helper code which this ReliableEndpoint will use to send and receive packets so that it knows how to interact with your socket (in this case, a Client instance), and then _instead_ of sending payloads via the Client class and receiving payloads directly from it, you do _all_ of your sending and receiving via the ReliableEndpoint class, which will use your provided callbacks to in turn handle all of the interaction with the Client instance.

There are three things to handle in this case. First of all, there's sending and receiving. Sending is done by providing a TransmitCallback:
```csharp
// whenever a payload is ready to be sent, we provide a custom function that uses the client instance's Send method to send the payload to the server.
reliableEndpoint.TransmitCallback = ( payload, size ) =>
{
    client.Send( payload, size );
};
```

And then, whenever you receive a payload via the client class, you need to pass this payload to the reliableEndpoint's ReceivePacket method:
```csharp
// when we get a packet from the server, direct it to the ReceivePacket method for processing.
client.OnMessageReceived += ( payload, size )=>
{
    reliableEndpoint.ReceivePacket( payload, size );
};
```

Now, a single packet generated by a ReliableEndpoint can actually contain multiple messages packed together, or it may only be part of a larger message. Upon receiving packets the ReliableEndpoint will reconstruct messages from individual fragments, as well as extract multiple messages packed into a single packet, and pass those to the ReceiveCallback. So use that to listen for when you receive a message:
```csharp
reliableEndpoint.ReceiveCallback = ( message, messageSize ) =>
{
    // this will be called with individual messages, so do whatever message receive processing you want here.
};
```

And now to send a message to the server you would use reliableEndpoint.SendMessage (which will in turn call your TransmitCallback which sends a message to the server via the Client object).

Now, this is just for the client. The server is much the same, but with a key difference: you should do this same logic _per remote client_. So for every RemoteClient that connects to a server, you should create a new ReliableEndpoint for that client. Similar setup:

- For the TransmitCallback, you would call remoteClient.SendPayload.
- In your handler for the Server object's OnClientMessageReceived event, you would look up that client's ReliableEndpoint object (for example, you could store a Dictionary<RemoteClient, ReliableEndpoint> for this) and call its ReceivePacket method.
- And finally, you can attach whatever custom code to each reliable endpoint's ReceiveCallback for processing messages from each client.

**Comment by Danila24ru** [comment]
Thank you very much. I integrated it. Its working very well. But I get some errors in console in client. 
Maybe I doing something wrong with reliableEndpoint.Update()?  I just added it to void Update() in client and in void Update() on server for each endpoints.
Client console and code:
![erere](https://user-images.githubusercontent.com/19823722/29528831-d7cc4b80-86b6-11e7-9c20-a37d07479e79.jpg)

![hahaw](https://user-images.githubusercontent.com/19823722/29529096-b8359f1e-86b7-11e7-87ea-7708cd85b20e.jpg)

**Comment by GlaireDaggers** [comment]
Hm, I'm curious about that EndOfStream error, is that related at all?
Also, if you could build a debug version of the DLL with the pdb file and drop that in so I can see the proper files and line numbers, that would help a lot since none of the unit tests throw any errors of the sort.

**Comment by Danila24ru** [comment]
List of things that I found: 
1) If one client disconnect, no one can't connect to server (or again) until server restart.
2) When I recieve message on clients again and again (position for example), packets always overwriting exist data. 
 for example: 
   1 packet (client gets): xxxxx
   2 packet                   :  yyy     ( <- i should get it)
 but i get this:                 yyyxx ( 2 packet include 1 ends)
    or this :                       xyy
 packets is distorted (maybe it is above endOf stream error).
3) When I set reliableEndpoint.Update(); (in client and server to void Update())  I get nullrefExpetinon (which above). 
When I set reliableNedpoint.Update(0.1f); i dont have any errors.
    
Look in my project, I can't find any mistakes(
(change ip address in inspector in server scene).
[Project.zip](https://github.com/KillaMaaki/ReliableNetcode.NET/files/1240423/Project.zip)

UPD: hmm.. 1) problem now somehow solved..

**Comment by GlaireDaggers** [comment]
Dropping in a debug build of the ReliableNetcode.NET project (including the PDB file) should produce correct line numbers in the Unity console, which would be very helpful for me if you could do that and take a snapshot. I can't reproduce those errors on my end (even outside of the unit tests with real code, as I'm currently building a multiplayer framework on top of it and it is connecting and sending just fine).

As for point 2... if you mean that the packet contains garbage data at the end left over from the previous packet, that is normal. This is because it reuses the buffer from the previous packet and doesn't clear it out. So if the new packet is smaller, it will not overwrite data beyond the end of it, leaving whatever was in the buffer before in place. This is what the `messageSize` parameter is for - it tells you how many bytes the actual valid data is. You should _not_ ever read past `messageSize`, as even if there's bytes beyond that they are only garbage left over from previous packets and are not valid whatsoever.

**Comment by Danila24ru** [comment]
![image](https://user-images.githubusercontent.com/19823722/29551486-531f852a-872c-11e7-80b7-5621017bc2e2.png)
Okay it's working now)
for point 2. As I understand I should just recieve packet like this ? 
```C#
    private void OnRecievedMessage(RemoteClient client, byte[] message, int size)
    {
        Debug.Log("Recieved message size(with garbage): " + message.Length + "Normal size: " + size);
        ByteBuffer buffer = new ByteBuffer(size);
        buffer.BufferCopy(message, 0, 0, size);

        switch (UnityPacketData.Deserialize(buffer.InternalBuffer))
        {
            case EPacketType.input:
 ```
and for point 1: After some client timed out, server ignore any client connections.

**Comment by GlaireDaggers** [comment]
I'll look into timing out. I don't think the base Netcode lib should have any problems with that, but I'll check anyway.

As far as receiving packets, I'd say just make your deserializer take a length parameter instead of reading to the end of a packet. That'd be better than copying it into a new byte buffer, since that's 100% equivalent to just allocating a new array and copying over the data every time - unless you're pooling the buffer, but in that case you run into the same problem and InternalBuffer will contain garbage data anyway. Or you could pool the byte buffer but make your Deserialize function take a ByteBuffer _instead_ of an array. There's a BufferPool class for pooling byte buffers.

**Comment by GlaireDaggers** [comment]
You may want to try updating to the latest ReliableNetcode commit I just pushed. It fixes an issue that was giving me a lot of (at first, seemingly unrelated) grief and bugs in my own project (turns out a single extra byte was being written to the buffer that wasn't supposed to be, and was causing the receiving end to try to read past the end of the buffer).

EDIT: Made another push which fixes a few critical issues with packet acking and message size validation. Seems to be working fine on my end now.

EDIT 2: I've also just now made a push to Netcode.IO.NET. This actually may be the root cause of your problem where sometimes clients would just start timing out for no apparent reason - intermittently, a ConnectionReset socket exception would be triggered upon a client disconnecting, and my socket code would simply stop processing messages entirely, causing messages to simply never be received past that point. It now checks if the socket exception is a ConnectionReset, and if so simply ignores the exception and continues.

**Comment by Danila24ru** [comment]
Thank you. Now it's working perfectly)
btw, I had an issue with garbage  because when I recieved message , I used ByteBuffer.InternalBuffer.Length instead ByteBuffer.Length (I thought that it's identic ¯\_(ツ)_/¯)
